const GET_WATCHLIST_STARTED = 'screens/watchlist/GET_WATCHLIST_STARTED';
const GET_WATCHLIST_STARTED = 'screens/watchlist/GET_WATCHLIST_SUCCESS';
const GET_WATCHLIST_FAILURE = 'screens/watchlist/GET_WATCHLIST_FAILURE';

export default {
  GET_WATCHLIST_STARTED,
  GET_WATCHLIST_STARTED,
  GET_WATCHLIST_FAILURE
};
