const GET_TRENDING_MOVIES_STARTED = 'screens/home/GET_TRENDING_MOVIES_STARTED';
const GET_TRENDING_MOVIES_SUCCESS = 'screens/home/GET_TRENDING_MOVIES_SUCCESS';
const GET_TRENDING_MOVIES_FAILURE = 'screens/home/GET_TRENDING_MOVIES_FAILURE';

const GET_MOVIES_STARTED = 'screens/home/GET_MOVIES_STARTED';
const GET_MOVIES_SUCCESS = 'screens/home/GET_MOVIES_SUCCESS';
const GET_MOVIES_FAILURE = 'screens/home/GET_MOVIES_FAILURE';

const SEARCH_MOVIES_STARTED = 'screens/home/SEARCH_MOVIES_STARTED';
const SEARCH_MOVIES_SUCCESS = 'screens/home/SEARCH_MOVIES_SUCCESS';
const SEARCH_MOVIES_FAILURE = 'screens/home/SEARCH_MOVIES_FAILURE';

export default {
  GET_TRENDING_MOVIES_STARTED,
  GET_TRENDING_MOVIES_SUCCESS,
  GET_TRENDING_MOVIES_FAILURE,
  SEARCH_MOVIES_STARTED,
  SEARCH_MOVIES_SUCCESS,
  SEARCH_MOVIES_FAILURE,
};
