const GET_TRENDING_MOVIES_STARTED = 'screens/home/GET_TRENDING_MOVIES_STARTED';
const GET_TRENDING_MOVIES_SUCCESS = 'screens/home/GET_TRENDING_MOVIES_SUCCESS';
const GET_TRENDING_MOVIES_FAILURE = 'screens/home/GET_TRENDING_MOVIES_FAILURE';

const GET_POPULAR_MOVIES_STARTED = 'screens/home/GET_POPULAR_MOVIES_STARTED';
const GET_POPULAR_MOVIES_SUCCESS = 'screens/home/GET_POPULAR_MOVIES_SUCCESS';
const GET_POPULAR_MOVIES_FAILURE = 'screens/home/GET_POPULAR_MOVIES_FAILURE';

const GET_REFRESH_MOVIES_STARTED = 'screens/home/GET_REFRESH_MOVIES_STARTED';
const GET_REFRESH_MOVIES_SUCCESS = 'screens/home/GET_REFRESH_MOVIES_SUCCESS';
const GET_REFRESH_MOVIES_FAILURE = 'screens/home/GET_REFRESH_MOVIES_FAILURE';

const SEARCH_MOVIES_STARTED = 'screens/home/SEARCH_MOVIES_STARTED';
const SEARCH_MOVIES_SUCCESS = 'screens/home/SEARCH_MOVIES_SUCCESS';
const SEARCH_MOVIES_FAILURE = 'screens/home/SEARCH_MOVIES_FAILURE';

export default {
  GET_TRENDING_MOVIES_STARTED,
  GET_TRENDING_MOVIES_SUCCESS,
  GET_TRENDING_MOVIES_FAILURE,
  GET_POPULAR_MOVIES_STARTED,
  GET_POPULAR_MOVIES_SUCCESS,
  GET_POPULAR_MOVIES_FAILURE,
  GET_REFRESH_MOVIES_STARTED,
  GET_REFRESH_MOVIES_SUCCESS,
  GET_REFRESH_MOVIES_FAILURE,
  SEARCH_MOVIES_STARTED,
  SEARCH_MOVIES_SUCCESS,
  SEARCH_MOVIES_FAILURE,
};
