const GET_MOVIE_STARTED = 'screens/moviedetails/GET_MOVIE_STARTED';
const GET_MOVIE_SUCCESS = 'screens/moviedetails/GET_MOVIE_SUCCESS';
const GET_MOVIE_FAILURE = 'screens/moviedetails/GET_MOVIE_FAILURE';

const GET_REVIEWS_STARTED = 'screens/moviedetails/GET_REVIEWS_STARTED';
const GET_REVIEWS_SUCCESS = 'screens/moviedetails/GET_REVIEWS_SUCCESS';
const GET_REVIEWS_FAILURE = 'screens/moviedetails/GET_REVIEWS_FAILURE';

const GET_RATINGS_STARTED = 'screens/moviedetails/GET_RATINGS_STARTED';
const GET_RATINGS_SUCCESS = 'screens/moviedetails/GET_RATINGS_SUCCESS';
const GET_RATINGS_FAILURE = 'screens/moviedetails/GET_RATINGS_FAILURE';

const POST_RATING_STARTED = 'screens/moviedetails/POST_RATING_STARTED';
const POST_RATING_SUCCESS = 'screens/moviedetails/POST_RATING_SUCCESS';
const POST_RATING_FAILURE = 'screens/moviedetails/POST_RATING_FAILURE';

const DELETE_RATING_STARTED = 'screens/moviedetails/DELETE_RATING_STARTED';
const DELETE_RATING_SUCCESS = 'screens/moviedetails/DELETE_RATING_SUCCESS';
const DELETE_RATING_FAILURE = 'screens/moviedetails/DELETE_RATING_FAILURE';

const ADD_WATCHLIST_STARTED = 'screens/moviedetails/ADD_WATCHLIST_STARTED';
const ADD_WATCHLIST_SUCCESS = 'screens/moviedetails/ADD_WATCHLIST_SUCCESS';
const ADD_WATCHLIST_FAILURE = 'screens/moviedetails/ADD_WATCHLIST_FAILURE';

export default {
  GET_MOVIE_STARTED,
  GET_MOVIE_SUCCESS,
  GET_MOVIE_FAILURE,

  GET_REVIEWS_STARTED,
  GET_REVIEWS_SUCCESS,
  GET_REVIEWS_FAILURE,

  GET_RATINGS_STARTED,
  GET_RATINGS_SUCCESS,
  GET_RATINGS_FAILURE,

  POST_RATING_STARTED,
  POST_RATING_SUCCESS,
  POST_RATING_FAILURE,

  DELETE_RATING_STARTED,
  DELETE_RATING_SUCCESS,
  DELETE_RATING_FAILURE,

  ADD_WATCHLIST_STARTED,
  ADD_WATCHLIST_SUCCESS,
  ADD_WATCHLIST_FAILURE
};
